export enum StorageKey {
  ACCESS_TOKEN = "ACCESS_TOKEN",
  REFRESH_TOKEN = "REFRESH_TOKEN",
  CURRENT_USER = "CURRENT_USER",
  IS_LOGIN = "IS_LOGIN",
  IS_NOT_ALLOW_REQUEST_PERMISSION = "IS_NOT_ALLOW_REQUEST_PERMISSION",
  IS_ALLOW_REQUEST_PERMISSION = "IS_ALLOW_REQUEST_PERMISSION",
  APP_LANGUAGE = "APP_LANGUAGE",
}
